import React from 'react';
import { X, FileCheck, Shield, BookOpen, AlertCircle } from 'lucide-react';

export default function TermsModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed',
      inset: 0,
      zIndex: 250,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      padding: '20px',
    }}>
      <div style={{
        width: '100%',
        maxWidth: '720px',
        maxHeight: '85vh',
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border-highlight)',
        borderRadius: 'var(--radius-md)',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}>
        {/* Header */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '16px 24px',
          borderBottom: '1px solid var(--border-subtle)',
          background: 'var(--bg-tertiary)',
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileCheck size={18} color="var(--accent-cyan)" />
            <h2 style={{ fontSize: '1.15rem', color: 'var(--text-primary)' }}>
              Terms and Conditions &bull; Academic Honor Code
            </h2>
          </div>
          <button onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div style={{
          padding: '24px',
          overflowY: 'auto',
          fontSize: '0.9rem',
          color: 'var(--text-secondary)',
          lineHeight: '1.6',
        }}>
          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-primary)', marginBottom: '6px' }}>
              1. Purpose and Educational Scope
            </h3>
            <p>
              Project Builder is an engineering specification and architecture planning tool designed for undergraduate
              and postgraduate students. All generated blueprints, architecture diagrams, database schemas, and roadmaps
              serve as reference specifications to guide development.
            </p>
          </div>

          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-primary)', marginBottom: '6px' }}>
              2. Academic Integrity and Originality
            </h3>
            <p>
              Users agree to abide by their institution's academic honor code. Specifications generated by Project Builder
              must be implemented directly by the project team. Direct submission of blueprint text as student implementation
              work without attribution constitutes a violation of university guidelines.
            </p>
          </div>

          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-primary)', marginBottom: '6px' }}>
              3. No Academic Evaluation Guarantee
            </h3>
            <p>
              Project Builder provides technical templates based on established software engineering standards. The platform
              does not guarantee project approval, external evaluation scores, viva examination marks, or university degree awards.
              Project evaluation remains the sole prerogative of the university board and department evaluators.
            </p>
          </div>

          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-primary)', marginBottom: '6px' }}>
              4. Intellectual Property
            </h3>
            <p>
              Source code, implementations, and custom datasets created by students based on these blueprints remain the
              intellectual property of the respective students and their affiliated institutions.
            </p>
          </div>

          <div style={{ marginBottom: '20px' }}>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-primary)', marginBottom: '6px' }}>
              5. Acceptable Use and Security
            </h3>
            <p>
              Users shall not exploit API endpoints, execute automated load attacks, upload corrupted or malicious payloads,
              or attempt unauthorized privilege escalation. Violations will result in account suspension and access revocation.
            </p>
          </div>

          <div>
            <h3 style={{ fontSize: '1rem', color: 'var(--text-primary)', marginBottom: '6px' }}>
              6. Custom Domain and Infrastructure
            </h3>
            <p>
              When deployed on institutional or custom domains, the platform administrators are responsible for managing TLS
              certificates, secure secret keys, and database backups according to local compliance requirements.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div style={{
          padding: '14px 24px',
          borderTop: '1px solid var(--border-subtle)',
          display: 'flex',
          justifyContent: 'flex-end',
          background: 'var(--bg-tertiary)',
        }}>
          <button onClick={onClose} className="btn btn-primary btn-sm">
            Close &bull; Accept Terms
          </button>
        </div>
      </div>
    </div>
  );
}
