"""Technology catalogue for the 22 engineering areas every blueprint must cover.

STACK[area][level] -> {"tools": [...], "why": str, "practices": [...]}
DOMAIN_ADDONS[area][domain] -> extra tools appended when the idea uses that domain.
"""
from __future__ import annotations

AREAS: list[tuple[str, str]] = [
    ("backend", "Backend"),
    ("frontend", "Frontend"),
    ("database", "Database"),
    ("api", "API & Integration"),
    ("auth", "Authentication & Authorization"),
    ("ai_ml", "AI / Machine Learning"),
    ("deep_learning", "Deep Learning"),
    ("genai", "Generative AI / LLM"),
    ("cv", "Computer Vision"),
    ("nlp", "NLP (Natural Language Processing)"),
    ("training", "AI Model Training & Fine-tuning"),
    ("inference", "AI Model Deployment / Inference"),
    ("cloud", "Cloud & Deployment"),
    ("devops", "DevOps"),
    ("security", "Web Security"),
    ("testing", "Testing"),
    ("performance", "Performance Optimization"),
    ("git", "Version Control (Git/GitHub)"),
    ("system_design", "System Design & Architecture"),
    ("storage", "File / Cloud Storage"),
    ("third_party", "Third-Party Integrations"),
    ("monitoring", "Monitoring & Maintenance"),
]

B, I, A = "beginner", "intermediate", "advanced"

STACK: dict[str, dict[str, dict]] = {
    "backend": {
        B: {"tools": ["Python 3.12", "Flask or FastAPI", "Pydantic"], "why": "Python keeps the AI and web code in one language; FastAPI gives automatic API docs.",
            "practices": ["Keep routes thin and put logic in service functions", "Load the ML model once at startup, not per request", "Use environment variables for secrets"]},
        I: {"tools": ["FastAPI", "SQLAlchemy 2.0", "Alembic migrations", "Celery / RQ + Redis for background jobs"], "why": "Async FastAPI handles concurrent inference requests; background workers keep slow jobs off the request path.",
            "practices": ["Layered structure: routers → services → repositories", "Run long inference/training jobs in a task queue", "Version the API (/api/v1)"]},
        A: {"tools": ["FastAPI microservices", "Celery/Kafka workers", "gRPC between services", "Redis cache", "Pydantic Settings"], "why": "Separating the API gateway, inference service and workers lets each scale independently.",
            "practices": ["Domain-driven service boundaries", "Idempotent workers with retries & dead-letter queues", "Health/readiness endpoints for every service"]},
    },
    "frontend": {
        B: {"tools": ["HTML5", "CSS3", "JavaScript", "Bootstrap or Streamlit for quick ML demos"], "why": "Fastest path to a working, demo-able interface.",
            "practices": ["Mobile-first responsive layout", "Show loading states while the model predicts", "Validate inputs before upload"]},
        I: {"tools": ["React + Vite", "React Router", "Axios / fetch", "Chart.js / Recharts"], "why": "Component-based UI with rich dashboards and fast dev builds.",
            "practices": ["Reusable components + a design system", "Central API client with auth interceptor", "Lazy-load heavy pages"]},
        A: {"tools": ["Next.js / React + TypeScript", "TanStack Query", "Tailwind or CSS Modules", "PWA (Workbox)", "WebSockets"], "why": "Type safety, server rendering, offline support and real-time updates.",
            "practices": ["Strict TypeScript and ESLint", "Optimistic updates and caching", "Accessibility (WCAG 2.1 AA) audits"]},
    },
    "database": {
        B: {"tools": ["SQLite", "SQLAlchemy ORM"], "why": "Zero setup, file-based and perfect for a single-machine demo.",
            "practices": ["Normalise to 3NF", "Use foreign keys", "Never store raw images in the DB, store file paths"]},
        I: {"tools": ["PostgreSQL", "SQLAlchemy + Alembic", "Redis (cache/sessions)"], "why": "Production-grade relational DB with JSONB support and robust concurrency.",
            "practices": ["Index foreign keys and frequently filtered columns", "Use migrations for every schema change", "Daily automated backups"]},
        A: {"tools": ["PostgreSQL (managed: Supabase / RDS / Cloud SQL)", "Redis", "Read replicas", "Partitioned time-series tables"], "why": "High availability, scaling reads and handling large telemetry/history volumes.",
            "practices": ["Connection pooling (PgBouncer)", "Partition large tables by time", "Point-in-time recovery"]},
    },
    "api": {
        B: {"tools": ["REST + JSON", "Postman", "Swagger UI (auto-generated)"], "why": "Simple, well understood and easy to test.",
            "practices": ["Consistent resource naming (/api/scans)", "Correct HTTP status codes", "Document every endpoint"]},
        I: {"tools": ["OpenAPI 3", "Pagination & filtering", "Webhooks", "MQTT (for devices)"], "why": "Clear contracts between frontend, backend and devices.",
            "practices": ["Versioning (/api/v1)", "Standard error format", "Rate limiting per client"]},
        A: {"tools": ["API Gateway (Kong / Nginx)", "gRPC for internal calls", "WebSockets / SSE for streaming", "AsyncAPI for events"], "why": "Scalable, observable APIs and real-time streaming of inference results.",
            "practices": ["Contract tests between services", "Idempotency keys for writes", "Backward-compatible evolution"]},
    },
    "auth": {
        B: {"tools": ["Session or JWT login", "bcrypt password hashing"], "why": "Basic but secure user accounts.",
            "practices": ["Never store plain-text passwords", "Enforce password rules", "Logout clears tokens"]},
        I: {"tools": ["JWT access tokens", "Role-Based Access Control (RBAC)", "Google OAuth 2.0 (optional)"], "why": "Different permissions for users, staff and admins.",
            "practices": ["Check roles on the server, never only in the UI", "Short-lived tokens", "Resource-level ownership checks"]},
        A: {"tools": ["OAuth2 / OpenID Connect (Keycloak / Auth0 / Firebase Auth)", "Refresh-token rotation", "MFA / OTP", "Fine-grained permissions"], "why": "Enterprise-grade identity, SSO and audit compliance.",
            "practices": ["Token revocation list", "Audit log for sensitive actions", "Least-privilege service accounts"]},
    },
    "ai_ml": {
        B: {"tools": ["NumPy", "Pandas", "scikit-learn", "Matplotlib / Seaborn", "Jupyter / Google Colab"], "why": "The standard toolkit for data preparation, classical models and evaluation.",
            "practices": ["Train/validation/test split before any preprocessing", "Start with a simple baseline", "Report precision, recall, F1 not just accuracy"]},
        I: {"tools": ["scikit-learn pipelines", "XGBoost / LightGBM", "Optuna (hyper-parameter tuning)", "SHAP / LIME (explainability)", "MLflow (experiment tracking)"], "why": "Stronger models, reproducible experiments and explainable predictions.",
            "practices": ["Cross-validation", "Track every experiment (params, metrics, data version)", "Explain predictions to users"]},
        A: {"tools": ["MLflow Model Registry", "DVC (data versioning)", "Feature store (Feast)", "Evidently AI (drift)", "Ray / Dask for scale"], "why": "Full MLOps lifecycle: versioned data, registered models and drift monitoring.",
            "practices": ["Automated retraining pipeline", "Data & concept drift alerts", "Model cards documenting limitations and bias"]},
    },
    "deep_learning": {
        B: {"tools": ["TensorFlow/Keras or PyTorch", "Pre-trained models (transfer learning)", "Google Colab GPU"], "why": "Transfer learning gives strong results with small datasets and free GPUs.",
            "practices": ["Freeze the backbone, train the head, then fine-tune", "Data augmentation", "Early stopping"]},
        I: {"tools": ["PyTorch + Lightning", "torchvision / timm / Hugging Face", "Weights & Biases", "Mixed-precision training"], "why": "Flexible research-grade framework with clean training loops and tracking.",
            "practices": ["Learning-rate scheduling", "Stratified splits and class weighting", "Save best checkpoint by validation metric"]},
        A: {"tools": ["PyTorch distributed / DeepSpeed", "Custom architectures (Transformers, U-Net, LSTM)", "Knowledge distillation", "Quantisation-aware training"], "why": "State-of-the-art accuracy while keeping models small enough to deploy.",
            "practices": ["Ablation studies for every design choice", "Distil large models into small ones", "Benchmark latency, not only accuracy"]},
    },
    "genai": {
        B: {"tools": ["Gemini API / OpenAI API", "Prompt engineering", "LangChain (optional)"], "why": "Adds natural-language explanations or a help assistant with very little code.",
            "practices": ["Keep prompts in versioned templates", "Ask for structured JSON output", "Show an AI-generated disclaimer"]},
        I: {"tools": ["Retrieval-Augmented Generation (RAG)", "ChromaDB / FAISS / pgvector", "Sentence-Transformers embeddings", "LangChain / LlamaIndex"], "why": "Grounds the LLM on your own documents to reduce hallucinations and enable citations.",
            "practices": ["Chunking with overlap + metadata", "Cite sources in answers", "Guard against prompt injection"]},
        A: {"tools": ["Open models (Llama 3, Mistral, Gemma) via Ollama / vLLM", "LoRA / QLoRA fine-tuning (PEFT)", "Function calling / agents", "RAGAS / DeepEval evaluation", "Guardrails"], "why": "Lower cost, data privacy, domain specialisation and measurable answer quality.",
            "practices": ["Evaluation set with faithfulness & relevance metrics", "Token cost and latency budgets", "Output moderation and PII redaction"]},
    },
    "cv": {
        B: {"tools": ["OpenCV", "Pillow", "MediaPipe", "Keras pre-trained CNNs"], "why": "Classic image processing plus ready-made detectors for faces/hands/pose.",
            "practices": ["Resize & normalise images consistently", "Augment (flip, rotate, brightness)", "Test with real-world photos, not only dataset images"]},
        I: {"tools": ["YOLOv8 / Ultralytics", "U-Net (segmentation)", "Albumentations", "Roboflow (labelling)", "Grad-CAM"], "why": "Detection and segmentation with explainable heat-maps.",
            "practices": ["Label a custom dataset for your environment", "Use mAP / IoU for evaluation", "Visualise failure cases"]},
        A: {"tools": ["YOLOv8-seg / RT-DETR", "Multi-object tracking (ByteTrack)", "Vision Transformers", "OpenVINO / TensorRT", "Vision-language models"], "why": "Real-time video analytics on edge hardware with state-of-the-art models.",
            "practices": ["Profile FPS on target hardware", "Handle low light & motion blur", "Privacy: blur faces where not needed"]},
    },
    "nlp": {
        B: {"tools": ["NLTK / spaCy", "TF-IDF (scikit-learn)", "VADER / TextBlob"], "why": "Fast, interpretable text processing baselines.",
            "practices": ["Clean & normalise text", "Handle stop-words and lemmatisation", "Start with TF-IDF + Logistic Regression"]},
        I: {"tools": ["Hugging Face Transformers", "BERT / DistilBERT / IndicBERT", "Sentence-Transformers", "spaCy NER"], "why": "Contextual embeddings dramatically outperform bag-of-words.",
            "practices": ["Fine-tune on domain data", "Handle multilingual / code-mixed text", "Explain predictions with attention or LIME"]},
        A: {"tools": ["LLM fine-tuning (PEFT)", "Multilingual models (mT5, IndicTrans2)", "Whisper (speech-to-text)", "Hybrid search & re-rankers"], "why": "Multilingual, voice-enabled, domain-adapted language understanding.",
            "practices": ["Bias and toxicity evaluation", "Benchmarks per language", "Efficient inference with distillation"]},
    },
    "training": {
        B: {"tools": ["Google Colab / Kaggle Notebooks (free GPU)", "Keras model.fit", "Train/val/test split"], "why": "Free GPUs are enough for transfer learning on small datasets.",
            "practices": ["Fix random seeds for reproducibility", "Save model + preprocessing together", "Plot training vs validation curves"]},
        I: {"tools": ["PyTorch Lightning", "Optuna hyper-parameter search", "MLflow / W&B tracking", "Roboflow / Label Studio for labelling"], "why": "Systematic, trackable experiments instead of trial-and-error.",
            "practices": ["K-fold cross-validation", "Hyper-parameter sweeps", "Data versioning with DVC"]},
        A: {"tools": ["LoRA / QLoRA (PEFT)", "Hugging Face Trainer / Accelerate", "Cloud GPUs (Colab Pro, Kaggle, Lambda, Vertex AI)", "Active learning loop"], "why": "Fine-tune large models efficiently and keep improving with new data.",
            "practices": ["Continual learning from user feedback", "Automated evaluation gate before deployment", "Track compute cost per experiment"]},
    },
    "inference": {
        B: {"tools": ["Load model in Flask/FastAPI", "joblib / .h5 / .pt files"], "why": "Simplest way to serve predictions over HTTP.",
            "practices": ["Load model once at startup", "Validate input shape/type", "Return confidence scores"]},
        I: {"tools": ["ONNX Runtime", "TFLite", "Batching", "Background workers for heavy jobs"], "why": "2–5× faster, framework-independent inference.",
            "practices": ["Export to ONNX and verify outputs match", "Warm-up requests", "Timeouts and fallbacks"]},
        A: {"tools": ["NVIDIA Triton / TorchServe / BentoML", "vLLM for LLMs", "INT8 quantisation", "TensorRT / OpenVINO / TFLite Micro on edge"], "why": "High-throughput, low-latency serving in the cloud and on devices.",
            "practices": ["Dynamic batching", "A/B and canary model rollouts", "Latency SLOs (p95)"]},
    },
    "cloud": {
        B: {"tools": ["Render / Railway / PythonAnywhere (backend)", "Vercel / Netlify (frontend)", "Hugging Face Spaces (ML demo)"], "why": "Free tiers and one-click deploys, ideal for demos.",
            "practices": ["Keep secrets in platform env vars", "Use a custom domain + HTTPS", "Keep a demo video as backup"]},
        I: {"tools": ["Docker", "AWS (EC2, S3, RDS) / GCP (Cloud Run, Cloud SQL) / Azure", "Nginx reverse proxy"], "why": "Portable containers on mainstream cloud platforms.",
            "practices": ["Containerise every service", "Separate dev / prod environments", "Use managed databases"]},
        A: {"tools": ["Kubernetes (GKE / EKS) or Cloud Run", "Terraform (Infrastructure as Code)", "GPU nodes / serverless GPUs", "CDN (Cloudflare)"], "why": "Auto-scaling, reproducible infrastructure and global delivery.",
            "practices": ["Horizontal pod autoscaling", "Infrastructure changes via pull requests", "Budget alerts"]},
    },
    "devops": {
        B: {"tools": ["GitHub", "requirements.txt / package.json", "README run instructions"], "why": "Anyone (including examiners) can clone and run the project.",
            "practices": ["One-command setup script", "Pin dependency versions", "Keep a .env.example"]},
        I: {"tools": ["Docker + Docker Compose", "GitHub Actions CI (lint + test + build)", "Pre-commit hooks"], "why": "Automated quality checks on every push.",
            "practices": ["CI must pass before merge", "Build images in CI", "Automated deploy from main"]},
        A: {"tools": ["GitHub Actions CI/CD", "Container registry", "ArgoCD / Helm", "MLOps pipelines (Kubeflow / Vertex Pipelines)"], "why": "Continuous delivery of both code and models.",
            "practices": ["Blue-green / canary deploys", "Automated rollback", "Separate model and app release cycles"]},
    },
    "security": {
        B: {"tools": ["HTTPS", "Input validation", "Parameterised queries (ORM)", "bcrypt"], "why": "Covers the most common vulnerabilities from day one.",
            "practices": ["Validate file type and size on uploads", "Never commit secrets", "Escape output to prevent XSS"]},
        I: {"tools": ["OWASP Top 10 checklist", "CORS policy", "Rate limiting", "Security headers (CSP, HSTS)", "Dependabot"], "why": "Protects against brute force, XSS, CSRF and vulnerable dependencies.",
            "practices": ["Least-privilege DB user", "Encrypt sensitive data at rest", "Log authentication failures"]},
        A: {"tools": ["OWASP ZAP (DAST)", "Bandit / Semgrep (SAST)", "Secrets manager (Vault / AWS Secrets Manager)", "WAF", "Prompt-injection defences for LLMs"], "why": "Continuous security testing and defence in depth.",
            "practices": ["Threat modelling (STRIDE)", "Security scans in CI", "Incident response plan"]},
    },
    "testing": {
        B: {"tools": ["pytest", "Manual test cases (Excel)", "Postman"], "why": "Proves core features work before the demo.",
            "practices": ["Write test cases for each module", "Test invalid inputs", "Record model accuracy on a held-out test set"]},
        I: {"tools": ["pytest + coverage", "FastAPI TestClient", "Vitest / Jest + React Testing Library", "Locust (load)"], "why": "Automated unit, integration and API tests in CI.",
            "practices": ["≥ 70% backend coverage", "Mock external APIs", "Regression test for model performance"]},
        A: {"tools": ["Playwright / Cypress (E2E)", "Locust / k6 (load)", "Great Expectations (data tests)", "Model behavioural tests (CheckList)"], "why": "Confidence across UI, data quality, model behaviour and load.",
            "practices": ["Test pyramid", "Performance budgets in CI", "Fairness and robustness tests for the model"]},
    },
    "performance": {
        B: {"tools": ["Image compression before upload", "Pagination", "Caching model in memory"], "why": "Keeps the demo fast on modest hardware.",
            "practices": ["Resize images client-side", "Avoid N+1 queries", "Lazy-load images"]},
        I: {"tools": ["Redis caching", "DB indexing", "GZip compression", "Code-splitting", "Async I/O"], "why": "Reduces latency and server load as users grow.",
            "practices": ["Profile before optimising", "Cache repeated predictions", "Measure p95 latency"]},
        A: {"tools": ["CDN", "Model quantisation & batching", "Horizontal scaling", "Load testing (k6)", "Query plan analysis"], "why": "Sustains high concurrency at low cost.",
            "practices": ["Set SLOs and error budgets", "Autoscale on queue depth", "Track cost per 1,000 predictions"]},
    },
    "git": {
        B: {"tools": ["Git", "GitHub", "Feature branches"], "why": "History, backup and collaboration from day one.",
            "practices": ["Commit small, commit often", "Meaningful commit messages", ".gitignore for datasets, models and .env"]},
        I: {"tools": ["GitHub Flow", "Pull requests + code review", "Conventional Commits", "GitHub Projects (Kanban)", "Git LFS for models"], "why": "Structured teamwork with reviews and traceable tasks.",
            "practices": ["Protected main branch", "PR template with checklist", "Link commits to issues"]},
        A: {"tools": ["Git Flow / trunk-based development", "Semantic versioning + release tags", "CODEOWNERS", "Signed commits", "DVC for data/models"], "why": "Release management and reproducibility of code, data and models.",
            "practices": ["Automated changelogs", "Required status checks", "Version datasets alongside code"]},
    },
    "system_design": {
        B: {"tools": ["Monolithic MVC architecture", "Block diagram", "Use-case & sequence diagrams"], "why": "Simple to build and explain in the viva.",
            "practices": ["Separate UI, logic and data layers", "Draw DFD level 0/1", "Keep the model behind a single service function"]},
        I: {"tools": ["Modular monolith", "Background task queue", "Caching layer", "C4 model diagrams"], "why": "Clean module boundaries with async processing of heavy AI jobs.",
            "practices": ["Define module interfaces", "Async processing for slow tasks", "Document architecture decisions (ADRs)"]},
        A: {"tools": ["Microservices / event-driven architecture", "Message broker (Kafka / RabbitMQ)", "API gateway", "CQRS where useful"], "why": "Independent scaling and fault isolation of inference, ingestion and web tiers.",
            "practices": ["Design for failure (retries, circuit breakers)", "Capacity estimation", "Trade-off analysis (CAP, latency vs cost)"]},
    },
    "storage": {
        B: {"tools": ["Local file system (uploads/ folder)", "Unique file names (UUID)"], "why": "Simple and sufficient for a demo.",
            "practices": ["Store only file paths in DB", "Whitelist file extensions", "Limit upload size"]},
        I: {"tools": ["AWS S3 / Google Cloud Storage / Cloudinary", "Pre-signed URLs", "Image thumbnails"], "why": "Durable, scalable storage separated from the app server.",
            "practices": ["Private buckets + signed URLs", "Lifecycle rules for old files", "Virus/type scanning on upload"]},
        A: {"tools": ["Object storage + CDN", "Data lake for training data (S3 / GCS + Parquet)", "Model artifact store (MLflow / S3)", "Backups & cross-region replication"], "why": "Handles large datasets, models and media at scale.",
            "practices": ["Separate buckets for raw / processed / models", "Encryption with managed keys", "Retention and deletion policies"]},
    },
    "third_party": {
        B: {"tools": ["Email via SMTP / SendGrid", "Google Charts / Chart.js"], "why": "Quick wins that make the project feel complete.",
            "practices": ["Keep API keys server-side", "Handle API failures gracefully"]},
        I: {"tools": ["Twilio / WhatsApp Cloud API (alerts)", "Google Maps / Leaflet", "OpenWeather API", "Google OAuth"], "why": "Real-world notifications, maps and data enrichment.",
            "practices": ["Wrap each provider behind an interface", "Retry with exponential back-off", "Respect rate limits and quotas"]},
        A: {"tools": ["Payment gateway (Razorpay / Stripe)", "Firebase Cloud Messaging", "Search APIs", "Webhooks from external systems"], "why": "Production integrations for monetisation, push notifications and ecosystem connectivity.",
            "practices": ["Verify webhook signatures", "Idempotent handlers", "Sandbox vs live keys per environment"]},
    },
    "monitoring": {
        B: {"tools": ["Python logging", "Health-check endpoint", "Uptime check (UptimeRobot)"], "why": "Know when something breaks during demos.",
            "practices": ["Log errors with context", "Add /health endpoint", "Keep a known-issues list"]},
        I: {"tools": ["Structured JSON logs", "Sentry (error tracking)", "Prometheus metrics", "Grafana dashboards"], "why": "Visibility into errors, latency and usage.",
            "practices": ["Request IDs across logs", "Alert on error-rate spikes", "Track prediction confidence over time"]},
        A: {"tools": ["OpenTelemetry tracing", "Prometheus + Grafana + Alertmanager", "ELK / Loki logging", "Evidently / WhyLabs (model drift)"], "why": "Full observability of services and model quality in production.",
            "practices": ["SLO dashboards", "Automated drift-triggered retraining", "Runbooks for incidents"]},
    },
}

DOMAIN_ADDONS: dict[str, dict[str, list[str]]] = {
    "database": {"iot": ["TimescaleDB / InfluxDB (time-series)"], "genai": ["pgvector / ChromaDB (embeddings)"], "data": ["Parquet data lake"]},
    "api": {"iot": ["MQTT broker (Mosquitto / HiveMQ / AWS IoT Core)"], "genai": ["Server-Sent Events for token streaming"]},
    "storage": {"cv": ["Image dataset bucket with versioning"], "iot": ["Raw telemetry archive (Parquet)"]},
    "inference": {"iot": ["TensorFlow Lite Micro / Edge Impulse"], "cv": ["ONNX Runtime Web (in-browser)"], "genai": ["Response caching for repeated prompts"]},
    "monitoring": {"iot": ["Device heartbeat & battery monitoring"], "genai": ["LLM token cost & latency tracking (Langfuse)"]},
    "security": {"genai": ["Prompt-injection filtering", "PII redaction before LLM calls"], "iot": ["TLS for MQTT + per-device credentials"]},
    "testing": {"iot": ["Hardware-in-the-loop tests", "Sensor calibration test log"], "genai": ["LLM evaluation set (golden Q&A)"]},
}

INTEREST_INTEGRATIONS: dict[str, list[str]] = {
    "agriculture": ["OpenWeather API", "Google Translate / Bhashini (local languages)"],
    "healthcare": ["SMS/WhatsApp alerts to caregivers", "FHIR-compatible export (optional)"],
    "finance": ["Razorpay sandbox", "Email/SMS OTP"],
    "smart-city": ["Google Maps / Leaflet + OpenStreetMap", "data.gov.in open APIs"],
    "environment": ["OpenAQ / CPCB data API", "Leaflet maps"],
    "education": ["Google Classroom API", "Telegram bot"],
    "transport": ["Google Maps Directions", "Twilio SMS"],
    "accessibility": ["Web Speech API (TTS/STT)", "Bhashini speech APIs"],
    "retail": ["Barcode/QR scanning", "Email reports"],
    "manufacturing": ["Telegram alerts", "Modbus/OPC-UA gateway"],
    "energy": ["Tariff data APIs", "Solar irradiance API"],
    "security": ["Have I Been Pwned API", "reCAPTCHA"],
    "careers": ["LinkedIn job search (public)", "Google Calendar API"],
    "developer-tools": ["GitHub REST & Webhooks", "Slack notifications"],
    "media": ["News APIs", "Google Fact Check Tools API"],
    "infrastructure": ["Google Maps", "PDF report generation"],
    "safety": ["Twilio SMS", "GPS location sharing"],
}

HARDWARE_STACK = {
    B: {"tools": ["Arduino Uno / ESP32", "Breadboard prototyping", "Arduino IDE"], "why": "Cheap, well-documented and beginner-friendly.",
        "practices": ["Calibrate sensors before use", "Use a separate supply for motors", "Draw the circuit in Fritzing/Tinkercad first"]},
    I: {"tools": ["ESP32 (Wi-Fi/BLE)", "Raspberry Pi 4/5", "MQTT", "PlatformIO", "Fritzing / KiCad schematics"], "why": "Connected devices with enough compute for edge AI.",
        "practices": ["Debounce inputs and filter noisy readings", "Watchdog timers & auto-reconnect", "Enclosure and cable management"]},
    A: {"tools": ["Custom PCB (KiCad)", "Jetson Nano / Raspberry Pi 5 / ESP32-S3", "LoRa / BLE mesh", "OTA firmware updates", "TinyML"], "why": "Robust field-ready hardware with on-device intelligence.",
        "practices": ["Power budgeting & battery-life estimation", "OTA updates with rollback", "Environmental testing (heat, dust, water)"]},
}

# ── PHYSICAL & FABRICATION-FIRST ENGINEERING DISCIPLINES (22 AREAS) ───────────
PHYSICAL_AREAS: list[tuple[str, str]] = [
    ("cad_modeling", "CAD 3D Modeling & Kinematics"),
    ("fea_simulation", "FEA Structural & Stress Analysis"),
    ("cfd_aerodynamics", "CFD & Thermal Fluid Dynamics"),
    ("material_selection", "Material Selection & Metallurgy"),
    ("machining_subtractive", "Subtractive Machining (CNC & Lathe)"),
    ("forming_welding", "Sheet Metal Forming & Welding"),
    ("additive_mfg", "Additive Manufacturing (3D Printing)"),
    ("kinematics_transmission", "Kinematics & Power Transmission"),
    ("mechanical_bom", "Mechanical BOM & Procurement"),
    ("gdt_tolerances", "GD&T & Tolerance Engineering"),
    ("experimental_testing", "Physical Testing & Experimental Stress"),
    ("fatigue_endurance", "Fatigue, Vibration & Factor of Safety"),
    ("surface_treatment", "Surface Finishing & Corrosion Protection"),
    ("thermal_fluids", "Thermodynamics & Heat Transfer"),
    ("design_for_mfg", "Design for Manufacturing & Assembly (DFMA)"),
    ("fasteners_joining", "Fasteners, Joints & Mating Design"),
    ("quality_metrology", "Metrology & Quality Inspection"),
    ("safety_standards", "Machine Safety, Guarding & Ergonomics"),
    ("maintenance_tribology", "Tribology, Lubrication & Maintenance"),
    ("embedded_mechatronics", "Mechatronic Controls & Sensors (Conditional)"),
    ("drawing_standards", "Engineering Drafting & Drawing Sheets"),
    ("cost_estimation", "Fabrication Costing & Indian Market Sourcing"),
]

PHYSICAL_STACK: dict[str, dict[str, dict]] = {
    "cad_modeling": {
        B: {"tools": ["Autodesk Fusion 360", "SolidWorks (Parts & Assemblies)", "2D Orthographic Projections"],
            "why": "Parametric sketch-based solid modeling with standard assembly mates and drawing generation.",
            "practices": ["Fully define all 2D sketch entities", "Use standard concentric/coincident mates", "Avoid circular references in assemblies"]},
        I: {"tools": ["SolidWorks 2024", "SolidWorks Motion Study", "CATIA V5 Kinematics"],
            "why": "Multi-body kinematic linkage simulation, interference collision detection, and stroke calculation.",
            "practices": ["Validate degrees of freedom with Gruebler-Kutzbach formula", "Run interference checks at max travel limit", "Assign precise material densities to all components"]},
        A: {"tools": ["PTC Creo / Siemens NX", "Master Model Top-Down Assembly Architecture", "Dynamic Kinematic Synthesis"],
            "why": "Industrial master-model modeling ensuring instant propagation of geometry updates across hundreds of fabricated parts.",
            "practices": ["Skeleton modeling for linkage geometry", "Automated exploded view bill of materials", "Parametric equation-driven drive ratios"]},
    },
    "fea_simulation": {
        B: {"tools": ["SolidWorks Simulation Xpress", "Static Stress Linear Analysis"],
            "why": "Rapid verification that maximum operating stresses remain well below material yield limit.",
            "practices": ["Apply realistic fixed and roller constraints", "Check deformed shape for physical sanity", "Verify minimum Factor of Safety >= 2.0"]},
        I: {"tools": ["ANSYS Workbench Static Structural", "Quadratic Tetrahedral & Hexahedral Meshing", "Mesh Convergence Study"],
            "why": "High-accuracy finite element analysis with adaptive mesh refinement at critical fillet radii and hole edges.",
            "practices": ["Perform mesh convergence until stress variation < 3%", "Evaluate von Mises stress vs yield strength", "Check contact penetration between mated surfaces"]},
        A: {"tools": ["Abaqus FEA / Altair HyperMesh", "Non-linear Material Plasticity", "Modal Vibration & Harmonic Response"],
            "why": "Advanced non-linear contact analysis and natural frequency modal simulation to prevent catastrophic resonance.",
            "practices": ["Determine first 6 natural resonant frequencies", "Model bolt pre-load tensions realistically", "Verify shear stress with Tresca criteria"]},
    },
    "cfd_aerodynamics": {
        B: {"tools": ["SolidWorks Flow Simulation", "Laminar Internal Flow Contours"],
            "why": "Visualizes fluid velocity streamlines and pressure drop across internal passages.",
            "practices": ["Set appropriate computational domain boundaries", "Ensure non-reversing outflow conditions", "Monitor mass flow balance"]},
        I: {"tools": ["ANSYS Fluent", "k-epsilon Realizable Turbulence Model", "Aerodynamic Drag Coefficient (Cd)"],
            "why": "Calculates turbulent boundary layer separation, wake vortices, and aerodynamic drag/lift forces.",
            "practices": ["Maintain boundary layer y+ values < 5 for wall resolution", "Conduct second-order upwind discretization", "Validate against empirical flat plate/airfoil data"]},
        A: {"tools": ["OpenFOAM", "ANSYS Fluent Multiphase / CHT", "Conjugate Heat Transfer Analysis"],
            "why": "Coupled fluid-solid thermal dissipation simulation for radiators, heat sinks, and aerodynamic fairings.",
            "practices": ["Grid convergence index (GCI) verification", "Thermal contact resistance at interfaces", "Transient vortex shedding simulation"]},
    },
    "material_selection": {
        B: {"tools": ["Aluminium 6061-T6", "Mild Steel AISI 1018", "PLA / PETG 3D Printing Filaments"],
            "why": "Readily accessible in Indian local industrial markets with predictable yield strengths and easy machinability.",
            "practices": ["Use Al 6061 for lightweight brackets", "Use MS 1018 for high-impact structural mounts", "Consult manufacturer tensile yield specs"]},
        I: {"tools": ["Aluminium 7075-T6", "EN8 / EN24 Hardened Alloy Steel", "Carbon Fiber Composite Plates (3K Twill)"],
            "why": "High strength-to-weight ratio materials suitable for drive shafts, gears, and structural aerospace/automotive ribs.",
            "practices": ["Select EN8 for induction-hardened drive shafts", "Account for carbon fiber anisotropic stiffness", "Prevent galvanic corrosion between carbon fiber and aluminum"]},
        A: {"tools": ["Ashby Material Selection Methodology", "CES EduPack", "Titanium Grade 5 (Ti-6Al-4V) / Maraging Steel"],
            "why": "Multi-objective material performance index optimization balancing specific strength, fracture toughness, and cost.",
            "practices": ["Maximize sigma_y / rho performance index", "Evaluate thermal expansion mismatch coefficients", "Certify material batch test reports (MTR)"]},
    },
    "machining_subtractive": {
        B: {"tools": ["Conventional Centre Lathe", "Drill Press", "Pedestal Grinder"],
            "why": "Manual machining for standard cylindrical turning, facing, drilling, and deburring operations.",
            "practices": ["Calculate spindle RPM from surface cutting speed (V = pi*D*N/1000)", "Use adequate soluble oil cutting coolant", "Deburr all sharp edges immediately"]},
        I: {"tools": ["CNC 3-Axis Vertical Machining Centre (VMC)", "CNC Lathe Turning", "End Mills & Carbide Inserts"],
            "why": "High-precision computer numerical control machining for bearing bores, slots, and complex profiles.",
            "practices": ["Generate G-code via CAM with toolpath simulation", "Implement climb milling for superior surface finish", "Establish zero reference workpiece offsets (G54)"]},
        A: {"tools": ["CNC 5-Axis Milling", "Wire EDM (Electrical Discharge Machining)", "Precision Surface Grinding"],
            "why": "Micron-level tolerances for hardened keyways, internal splines, and complex aerodynamic impellers.",
            "practices": ["Optimize chip load and tool overhang to prevent deflection", "Use Wire EDM for heat-treated hardened tool steel", "Verify spindle vibration with accelerometers"]},
    },
    "forming_welding": {
        B: {"tools": ["MIG (GMAW) Arc Welding", "Manual Sheet Metal Shearing", "Hand Brake Bending"],
            "why": "Cost-effective fabrication of chassis frames, brackets, and structural sheet enclosures.",
            "practices": ["Tack weld joints before continuous beads to prevent distortion", "Clean mill scale and rust before welding", "Calculate sheet bend deduction"]},
        I: {"tools": ["TIG (GTAW) Welding with Argon Gas", "CNC Hydraulic Press Brake", "CNC Fiber Laser Sheet Cutting"],
            "why": "High-integrity, spatter-free welds on aluminium/chromoly tubing and precise sheet metal bends.",
            "practices": ["Use 100% Argon shielding gas for aluminium TIG", "Calculate K-factor for precise bend allowances", "Inspect weld throat thickness with fillet gauges"]},
        A: {"tools": ["Orbital TIG Welding", "Robotic Spot Welding", "Hydroforming / Roll Cage Fabrication Fixtures"],
            "why": "Motorsport-grade chassis tubular spaceframe fabrication with zero angular distortion.",
            "practices": ["Build rigid fabrication jigs and fixtures", "Post-weld stress relief heat treatment", "Purge oxygen from tubular backside using argon backing gas"]},
    },
    "additive_mfg": {
        B: {"tools": ["FDM 3D Printing (Creality / Bambu Lab)", "PLA / PETG Filaments", "Cura / PrusaSlicer"],
            "why": "Rapid prototyping of prototype enclosures, sensor mounting brackets, and ergonomic handles.",
            "practices": ["Orient parts so layer lines are parallel to principal shear loads", "Use minimum 4 wall perimeters for threaded inserts", "Set 20-30% gyroid infill"]},
        I: {"tools": ["SLA / MSLA Resin Printing", "Carbon-Fiber Nylon (PA-CF) FDM", "Enclosed High-Temp Printer"],
            "why": "High-stiffness, isotropic prototype components resistant to mechanical oil and engine bay temperatures.",
            "practices": ["Dry hygroscopic nylon filaments in dehydrator before printing", "Use brass heat-set threaded inserts for fasteners", "Post-cure SLA resin under UV chamber"]},
        A: {"tools": ["SLS Nylon (Selective Laser Sintering)", "DMLS Metal 3D Printing (Direct Metal Laser Sintering)", "Topology Optimization"],
            "why": "Generative design components with organic load-bearing forms impossible to machine with CNC tooling.",
            "practices": ["Run topology optimization minimizing mass while targeting FOS >= 2.5", "Design self-supporting overhang angles (> 45 deg)", "Perform stress-relief annealing prior to support removal"]},
    },
    "kinematics_transmission": {
        B: {"tools": ["Spur Gear Trains", "Timing Belts (GT2 / HTD 5M)", "Flexible Spider Jaw Couplers"],
            "why": "Standard power transmission converting motor rotation into reduced speed and multiplied torque.",
            "practices": ["Calculate gear ratio (i = N2 / N1)", "Ensure timing belt tension is neither loose nor over-stressed", "Align motor and drive shafts within 0.1 mm"]},
        I: {"tools": ["Precision Ball Screws (SFU1605 / 2005)", "Helical / Planetary Gearbox", "Four-Bar Linkage Synthesis"],
            "why": "High mechanical efficiency (> 90%) linear drive transmission with minimal backlash.",
            "practices": ["Calculate lead screw critical buckling speed", "Pre-load ball nut to eliminate axial play/backlash", "Validate transmission angle between 45 and 135 degrees"]},
        A: {"tools": ["Harmonic Drive / Cycloidal Reducer", "Epicyclic Compound Gearboxes", "Six-Bar Complex Kinematics"],
            "why": "Zero-backlash, high-reduction compact drives for robotic joints and precision steering actuators.",
            "practices": ["Calculate contact stress using Lewis and Hertz equations", "Select surface case-hardening depth (HRC 58-62)", "Perform dynamic balance at full operating RPM"]},
    },
    "mechanical_bom": {
        B: {"tools": ["Standard Deep Groove Ball Bearings (608RS / 6204)", "Metric Fasteners (M4-M8)", "Indian Market Vendor Catalog"],
            "why": "Sourcing off-the-shelf catalog parts drastically reduces fabrication turnaround time and cost.",
            "practices": ["Procure bearings from authorized SKF/FAG dealers", "Verify shaft fit tolerance matching bearing inner diameter", "Maintain 10% spare hardware inventory"]},
        I: {"tools": ["Linear Motion Rails (MGN12 / HGR20)", "High-Tensile Grade 8.8 Fasteners", "Induction Hardened Chrome Shafts (CK45)"],
            "why": "Heavy-duty industrial automation motion hardware with Indian pricing transparency (Robu.in / local auto hubs).",
            "practices": ["Calculate required dynamic load capacity C vs static load C0", "Specify stainless or zinc-plated coating to resist rust", "Tabulate exact pricing in INR including GST"]},
        A: {"tools": ["Angular Contact Duplex Bearings", "Ball Bushing Blocks with Wiper Seals", "ISO Standardized Actuator Procurement"],
            "why": "Pre-loaded high-rigidity bearing arrangements supporting combined simultaneous radial and axial thrust loads.",
            "practices": ["Calculate bearing L10 fatigue life rating in operating hours", "Account for thermal shaft expansion when locking bearings", "Issue itemized engineering procurement bill of materials"]},
    },
    "gdt_tolerances": {
        B: {"tools": ["ISO 286 Fits & Limits (H7/h6, H7/g6)", "Dimensional Linear Tolerances (+/- 0.1 mm)"],
            "why": "Prevents loose bearing chatter or impossible press-fit assembly during workshop fabrication.",
            "practices": ["Use H7 hole tolerance for reamed bearing housings", "Use g6 shaft tolerance for slide fits", "Specify chamfers on all entry holes for ease of assembly"]},
        I: {"tools": ["ASME Y14.5 / ISO 1101 GD&T", "Flatness, Perpendicularity, Concentricity Callouts", "Datum Reference Frames"],
            "why": "Defines geometric feature control frames ensuring interchangeable assembly across multiple fabricators.",
            "practices": ["Establish functional datum features (A, B, C)", "Limit shaft runout to <= 0.02 mm to prevent vibration", "Apply Maximum Material Condition (MMC) where advantageous"]},
        A: {"tools": ["Tolerance Stack-Up Worst-Case Analysis", "Root Sum Squares (RSS) Statistical Tolerancing", "CMM Coordinate Inspection Protocol"],
            "why": "Rigorous tolerance loop accumulation analysis ensuring 99.73% assembly yield without manual fitting.",
            "practices": ["Conduct loop closure tolerance analysis", "Evaluate thermal expansion effect on running clearances", "Produce formal CMM dimensional inspection sign-off sheets"]},
    },
    "experimental_testing": {
        B: {"tools": ["Digital Vernier Caliper", "Dial Indicator with Magnetic Base", "Digital Force Gauge / Spring Balance"],
            "why": "Fundamental dimensional and physical measurement verifying prototype dimensions against CAD drawings.",
            "practices": ["Calibrate vernier zero error before measuring", "Measure diameter across three orthogonal positions", "Record dial gauge deflection under gradual manual load"]},
        I: {"tools": ["ASTM E8 Tensile Coupon Testing", "Strain Gauge Rosettes with Quarter-Bridge Circuit", "Tachometer & Thermal Thermocouples"],
            "why": "Empirical stress measurement on fabricated welded joints and physical prototype structural elements.",
            "practices": ["Bond strain gauge using cyanoacrylate with zero bubble voids", "Calibrate strain gauge gauge factor (GF)", "Record temperature rise during continuous operating cycle"]},
        A: {"tools": ["Multi-Channel Dynamic DAQ (Data Acquisition)", "Tri-Axial Piezoelectric Accelerometers", "Brinell / Rockwell Hardness Tester"],
            "why": "Laboratory-grade physical validation capturing dynamic strain, vibration spectral FFT, and surface hardness.",
            "practices": ["Perform FFT vibration spectrum analysis to identify harmonics", "Test coupon hardness per ASTM E18 standard", "Correlate physical experimental strain directly with FEA model"]},
    },
    "fatigue_endurance": {
        B: {"tools": ["Factor of Safety (FOS) Calculation", "S-N Wöhler Curve Principles", "Stress Concentration Factor (Kt)"],
            "why": "Ensures the structure survives continuous cyclic operation without sudden brittle fracture.",
            "practices": ["Maintain minimum FOS >= 2.5 for static loads", "Provide generous fillet radii (R >= 3 mm) at all shaft steps", "Avoid drilling holes in high-tension flanges"]},
        I: {"tools": ["Goodman & Gerber Fatigue Criteria", "Endurance Limit (Se) Surface Finish Factors", "Dynamic Balancing (IS 13917)"],
            "why": "Accounts for alternating cyclic stress with mean tensile stress offset to prevent fatigue crack initiation.",
            "practices": ["Calculate modified endurance limit with Marin factors", "Balance all rotating shafts dynamically per ISO 1940 Grade G2.5", "Polish high-stress surface zones to Ra < 0.8 um"]},
        A: {"tools": ["Fracture Mechanics (Paris Law Crack Growth)", "Rainflow Cycle Counting", "Vibration Shaker Fatigue Testing"],
            "why": "Life-prediction analysis under random operational load spectra and shock loading.",
            "practices": ["Calculate stress intensity factor K_I vs fracture toughness K_IC", "Execute 100,000 cycle endurance bench test", "Inspect post-test structure using dye penetrant NDT"]},
    },
    "surface_treatment": {
        B: {"tools": ["Wire Brushing / Sanding", "Anti-Corrosion Red Oxide Primer", "Synthetic Enamel Spray Paint"],
            "why": "Simple workshop surface preparation preventing immediate atmospheric oxidation of mild steel.",
            "practices": ["Degrease surfaces with acetone or thinner before primer", "Apply two light coats rather than one heavy sagging coat", "Allow 24-hour curing before assembly"]},
        I: {"tools": ["Sulphuric Acid Hard Anodizing (Type III)", "Zinc Electroplating (Trivalent Chrome Passivation)", "Powder Coating"],
            "why": "Durable, scratch-resistant corrosion protection for aluminium brackets and steel structural frames.",
            "practices": ["Specify 25-50 micron anodize layer for aluminium wear surfaces", "Bake electroplated high-tensile steel to prevent hydrogen embrittlement", "Mask threaded holes before powder coating"]},
        A: {"tools": ["Electroless Nickel Plating (ENP)", "Thermal Spray Ceramic Coating", "Plasma Nitriding (Hardness > 65 HRC)"],
            "why": "Extreme wear and heat resistant surface engineering for high-friction gears and cylinder liners.",
            "practices": ["Verify plating uniformity across complex internal bores", "Inspect coating adhesion per ASTM D3359 cross-hatch test", "Measure surface roughness Ra before and after coating"]},
    },
    "thermal_fluids": {
        B: {"tools": ["Aluminium Extruded Pin-Fin Heat Sinks", "12V Brushless Axial Cooling Fans", "Thermal Conductive Paste"],
            "why": "Cost-effective forced-air cooling preventing overheating of motors, drivers, and power electronics.",
            "practices": ["Apply paper-thin layer of thermal grease without air gaps", "Position cooling fan for intake rather than suction where possible", "Calculate natural convective dissipation area"]},
        I: {"tools": ["Plate-Fin Heat Exchangers", "Thermal Circuit Network Analysis (R_th)", "Heat Pipe Integration"],
            "why": "Thermal resistance network design maintaining component junction temperatures safely below 75 deg C.",
            "practices": ["Calculate total thermal resistance R_total = R_jc + R_cs + R_sa", "Ensure intake airflow is not recirculating hot exhaust", "Size radiator surface area to handle peak thermal wattage"]},
        A: {"tools": ["Liquid Cooling Closed Loop (Water-Glycol)", "CFD Conjugate Heat Transfer (CHT)", "Thermoelectric Peltier Optimization"],
            "why": "High-density thermal extraction for electric vehicle battery packs, high-power BLDC motors, and laser modules.",
            "practices": ["Maintain coolant flow velocity between 1.0 and 2.0 m/s to prevent erosion", "Evaluate pressure drop through cooling channels", "Include coolant flow switch and temperature cut-off failsafes"]},
    },
    "design_for_mfg": {
        B: {"tools": ["Boothroyd & Dewhurst DFMA Principles", "Standard Metric Stock Sizing", "Fastener Standardization"],
            "why": "Minimizes machining waste and ensures components can be fabricated on standard workshop machinery.",
            "practices": ["Design around available commercial bar and plate stock thicknesses", "Use identical bolt sizes (e.g. all M6) across the assembly", "Ensure open tool access for Allen wrenches"]},
        I: {"tools": ["Machining Toolpath Clearance Optimization", "Symmetrical Part Design", "Poka-Yoke Assembly Alignment Pins"],
            "why": "Eliminates operator assembly errors and avoids expensive custom tooling during fabrication.",
            "practices": ["Design internal radii larger than milling cutter radii (R_tool + 0.5 mm)", "Incorporate asymmetric dowel pins to prevent backwards assembly", "Minimize total unique part count in the BOM"]},
        A: {"tools": ["Modular Sub-Assembly Architecture", "Snap-Fits & Tab-and-Slot Laser Interlocks", "Fabrication Time & Cycle Cost Modeling"],
            "why": "Enables rapid self-locating laser-cut sheet metal welding without requiring dedicated holding jigs.",
            "practices": ["Use tab-and-slot joints for self-aligning chassis sheet fabrication", "Design modular sub-assemblies testable prior to final integration", "Conduct formal DFMA time reduction audit"]},
    },
    "fasteners_joining": {
        B: {"tools": ["Grade 8.8 Metric Allen Socket Screws (ISO 4762)", "Nyloc Locking Nuts (ISO 7040)", "Spring & Flat Washers"],
            "why": "Vibration-proof standard metric mechanical fasteners preventing loosening under operating loads.",
            "practices": ["Always use flat washers under nuts to distribute bearing stress", "Use Nyloc nuts on all vibrating structural joints", "Ensure at least 2 threads protrude beyond the nut"]},
        I: {"tools": ["High-Tensile Grade 10.9 & 12.9 Fasteners", "Torque Wrench Calibration", "Thread-Locking Adhesives (Loctite 243 / 270)"],
            "why": "Accurate bolt pre-load clamping force preventing joint slip and shear fatigue failure.",
            "practices": ["Calculate required bolt tightening torque T = K*F_pre*d", "Apply medium-strength blue threadlocker to set screws", "Ensure minimum thread engagement: 1.5x diameter in steel, 2x in aluminum"]},
        A: {"tools": ["VDI 2230 Systematic Bolted Joint Calculation", "Nord-Lock Wedge-Locking Washers", "Precision Dowel Pin Press Fits"],
            "why": "Aerospace-grade bolted joint calculation accounting for embedment, eccentric loading, and thermal differential.",
            "practices": ["Perform joint diagram analysis (clamp load vs working load)", "Use precision ground dowel pins to absorb shear loads, not bolts", "Verify safety factor against yield under proof load"]},
    },
    "quality_metrology": {
        B: {"tools": ["External Micrometer (0-25 mm, 0.01 mm precision)", "Steel Rule & Try Square", "Feeler Gauges"],
            "why": "Ensures all turned shafts and milled plates conform to drawing dimensions before final assembly.",
            "practices": ["Clean micrometer anvils and verify zero datum before measuring", "Use ratchet stop for consistent measurement force", "Measure flat surface squareness against try square"]},
        I: {"tools": ["Bore Dial Indicator", "Height Gauge with Granite Surface Plate", "Optical Profile Projector"],
            "why": "Accurate measurement of internal bearing bore diameters and geometric runout on precision surfaces.",
            "practices": ["Rock bore gauge to detect true minimum diameter reading", "Inspect components on calibrated Grade 0 granite surface plate", "Verify pitch and thread tooth geometry on profile projector"]},
        A: {"tools": ["Coordinate Measuring Machine (CMM)", "Laser Scanning Metrology", "Surface Roughness Tester (Mitutoyo Surftest)"],
            "why": "Automated 3D inspection verifying complex GD&T true position, profile of a surface, and micro-finish Ra.",
            "practices": ["Generate automated CMM inspection routines directly from CAD STEP files", "Verify surface roughness meets Ra <= 0.8 um for bearing journals", "Compile formal First Article Inspection (FAI) report"]},
    },
    "safety_standards": {
        B: {"tools": ["Mechanical Sheet Metal Belt Guards", "Emergency Stop Push Button (E-Stop)", "Workshop Safety Signage"],
            "why": "Prevents accidental operator contact with rotating gears, pulleys, and linear pinching points.",
            "practices": ["Enclose all moving belts and gears with fixed protective shrouds", "Locate E-Stop within immediate arm's reach of operator", "Ensure zero pinch points larger than 6 mm"]},
        I: {"tools": ["Safety Interlock Switches", "Polycarbonate Shatterproof Enclosures", "ISO 12100 Machinery Risk Assessment"],
            "why": "Automatic power cut-off when service doors or machine protective covers are opened.",
            "practices": ["Use positive-break safety limit switches", "Use optical grade polycarbonate (Lexan) for chip guarding, not acrylic", "Document risk matrix (severity, frequency, probability of avoidance)"]},
        A: {"tools": ["Safety Relay Modules (Category 3 / 4)", "Light Curtains & Perimeter Safety Monitoring", "Failsafe Mechanical Brakes"],
            "why": "Industrial SIL-2 / PL-d compliant dual-channel safety circuitry preventing accidental machine restart.",
            "practices": ["Wire E-stop circuits with dual redundant contacts", "Install spring-loaded mechanical failsafe brakes that clamp upon power loss", "Certify zero hazardous residual kinetic/hydraulic energy upon shutdown"]},
    },
    "maintenance_tribology": {
        B: {"tools": ["Lithium Base Multi-Purpose Grease (NLGI 2)", "ISO VG 68 Machine Oil", "Grease Nipples (M6)"],
            "why": "Ensures minimal boundary friction and prevents premature metal-to-metal galling.",
            "practices": ["Wipe grease fittings clean before injecting grease", "Apply oil to lead screws and linear guide rails weekly", "Check for oil leakage or seal degradation"]},
        I: {"tools": ["PTFE Dry Film Lubricant", "Synthetic EP2 Heavy-Duty Gear Oil", "Grease Seal Retaining Rings"],
            "why": "High-pressure additive lubrication preventing micro-pitting on gear teeth and sliding mechanisms.",
            "practices": ["Use dry PTFE lubricant in dusty or outdoor environments", "Monitor oil level in gearboxes using sight glass", "Inspect oil for metal shavings indicating abnormal wear"]},
        A: {"tools": ["Ferrographic Oil Analysis", "Vibration Shock Pulse Bearing Monitoring (SPM)", "Centralized Automated Lubrication System"],
            "why": "Predictive maintenance detecting microscopic bearing subsurface spalling well before catastrophic seizure.",
            "practices": ["Schedule lubrication cycles based on operating hours", "Perform shock pulse dBm/dBc measurements on bearing housings", "Calculate minimum elastohydrodynamic (EHD) oil film thickness"]},
    },
    "embedded_mechatronics": {
        B: {"tools": ["Arduino Uno R3", "L298N Motor Driver", "Microswitch Endstops"],
            "why": "Simple micro-controller actuation for homing axes and basic forward/reverse motion control.",
            "practices": ["Use external DC power supply for motors, never USB 5V", "Wire limit switches in normally-closed (NC) fail-safe mode", "Add flyback diodes across inductive solenoid coils"]},
        I: {"tools": ["Arduino Mega 2560 / ESP32", "TB6600 Stepper Driver (4A)", "HX711 Strain Gauge Load Cell Amplifier", "Rotary Optical Encoder"],
            "why": "Closed-loop position and force telemetry without requiring cloud or complex web frameworks.",
            "practices": ["Use opto-isolated step/direction inputs on stepper driver", "Set current limit DIP switches matching motor rated amps", "Use twisted-pair shielded cables for encoder and load cell signals"]},
        A: {"tools": ["STM32 Cortex-M4 / Teensy 4.1", "CAN Bus / RS485 Industrial Protocol", "Closed-Loop FOC BLDC Controller (ODrive / SimpleFOC)"],
            "why": "High-bandwidth Field-Oriented Control (FOC) motor driving with sub-millimeter trajectory execution.",
            "practices": ["Implement hardware watchdog timers", "Process encoder interrupts with dedicated hardware timers", "Provide transient TVS diode voltage spike protection on 24V power rails"]},
    },
    "drawing_standards": {
        B: {"tools": ["First Angle / Third Angle Projections", "Title Block with Scale & Author", "A3 Drawing Sheet Standard"],
            "why": "Communicates fabrication dimensions to machinists according to standard drafting conventions.",
            "practices": ["Consistently use Third Angle projection symbol", "Never duplicate dimensions on multiple views", "Include overall envelope dimensions (Length x Width x Height)"]},
        I: {"tools": ["ISO 128 Engineering Drawing Rules", "Section Views & Detail Enlargements", "Surface Roughness Symbols"],
            "why": "Clear visualization of internal cavities, cross-drilled holes, and required surface finishes.",
            "practices": ["Use hatching angles of 45 degrees for section planes", "Place detail callout circles with enlarged scales (2:1)", "Specify weld symbols (fillet, bevel, pitch) per ISO 2553"]},
        A: {"tools": ["Model-Based Definition (MBD / 3D Annotations)", "Full GD&T Feature Control Drawing Sets", "Manufacturing Process Routing Sheets"],
            "why": "Production-ready engineering drawings accompanied by step-by-step machining sequence sheets.",
            "practices": ["Generate complete drawing package (General Assembly, Sub-Assembly, Part drawings)", "Attach formal Engineering Change Order (ECO) revision block", "Include complete bill of materials table with material specifications"]},
    },
    "cost_estimation": {
        B: {"tools": ["Raw Material Weight-Based Costing", "Local Indian Hardware Retail Pricing (INR)", "Spreadsheet BOM"],
            "why": "Calculates realistic component procurement expenses within student capstone financial budgets.",
            "practices": ["Calculate stock raw weight = Volume * Density", "Include 10% material wastage allowance during cutting", "Account for 18% GST on procured items"]},
        I: {"tools": ["Machine-Hour Rate Estimation (Lathe/CNC/Laser)", "Standard Fabrication Labor Costing (INR/hr)", "Vendor Quotation Matrix"],
            "why": "Accurately models commercial manufacturing costs including tooling and machine shop time.",
            "practices": ["Benchmark lathe machining at Rs. 250-400/hour in local Indian industrial estates", "Obtain laser cutting quotations per meter of cut length", "Compare off-the-shelf purchase vs custom fabrication cost"]},
        A: {"tools": ["Activity-Based Costing (ABC)", "Break-Even Batch Size Analysis", "Life-Cycle Cost Estimation"],
            "why": "Analyzes the economic viability of scaling the capstone prototype to pilot batch manufacturing (100 units).",
            "practices": ["Determine fixed tooling costs vs variable per-unit material costs", "Calculate break-even production quantity", "Quantify operational energy consumption and maintenance expenditure"]},
    },
}
